# Generated by Django 5.0.1 on 2024-01-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentra', '0002_remove_renting_description_renting_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
