POST '127.0.0.1:8000 HTTP/1.1
header name: header value

content

###
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json 

{ "username": "jo2", "password": "h", "email": "adam@mail.com" }

###

###
GET http://127.0.0.1:8000/api/logout/ 
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/register/ 
Content-Type: application/json

{ "username": "jo3", "password": "h", "email": "adam@mail.com" }

###
###

GET http://127.0.0.1:8000/api/login/test_token/
Content-Type: application/json
Authorization: Token 6f5552f7b7e20cd53caa69e62c0a3826b9d1a8a0

###